name: Daily TLE Download

on:
  schedule:
    # 毎日 00:30 UTC（日本時間 09:30）
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: daily-tle
  cancel-in-progress: false

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run fetch script
        run: python scripts/fetch_tle.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.txt
          git diff --cached --quiet || git commit -m "Daily TLE update"
          git push
# force reindex
